--DROP TABLE IF EXISTS BUILDINGS_MAX, BUILDINGS_MAX_ERPS;
--CREATE TABLE BUILDINGS_MAX(UUEID VARCHAR, ID_BAT VARCHAR, AGGLO BOOLEAN, PERIOD VARCHAR(4), noiselevel DECIMAL(5,2));
--
--CREATE TABLE BUILDINGS_MAX_ERPS(UUEID VARCHAR, ID_ERPS VARCHAR,ERPS_NATUR VARCHAR, AGGLO BOOLEAN, PERIOD VARCHAR(4), noiselevel DECIMAL(5,2));
SET @ESTATUnitCode='${ESTATUnitCode}';

DROP TABLE IF EXISTS POPULATION_EXPOSURE;
CREATE TABLE POPULATION_EXPOSURE(PK VARCHAR, ESTATUnitCode VARCHAR DEFAULT @ESTATUnitCode, UUEID VARCHAR, EXPOSURETYPE VARCHAR,
 NOISELEVEL VARCHAR, EXPOSEDPEOPLE INT DEFAULT(0), EXPOSEDAREA REAL DEFAULT(0), EXPOSEDDWELLINGS INT DEFAULT(0),
 EXPOSEDHOSPITALS INT DEFAULT(0), EXPOSEDSCHOOLS INT DEFAULT(0), CPI INT DEFAULT(0), HA INT DEFAULT(0),
  HSD INT DEFAULT(0));

INSERT INTO POPULATION_EXPOSURE(PK, UUEID, EXPOSURETYPE, NOISELEVEL) SELECT CONCAT(CONCAT(UUEID, '_'), NOISELEVEL) PK,
UUEID, EXPOSURETYPE, NOISELEVEL FROM UUEIDS_LEVELS;

drop index if exists RECEIVERS_BUILDING_BUILD_PK;
create index RECEIVERS_BUILDING_BUILD_PK on RECEIVERS_BUILDING (BUILD_PK);

drop index if exists BUILDINGS_ERPS_ID_BAT  ;
create index BUILDINGS_ERPS_ID_BAT on  BUILDINGS_ERPS (ID_BAT);

