DROP TABLE IF EXISTS BUILDINGS_MAX, BUILDINGS_MAX_ERPS;
CREATE TABLE BUILDINGS_MAX(UUEID VARCHAR, ID_BAT VARCHAR, AGGLO BOOLEAN, PERIOD VARCHAR(4), noiselevel DECIMAL(5,2));

CREATE TABLE BUILDINGS_MAX_ERPS(UUEID VARCHAR, ID_ERPS VARCHAR,ERPS_NATUR VARCHAR, AGGLO BOOLEAN, PERIOD VARCHAR(4), noiselevel DECIMAL(5,2));

drop index if exists RECEIVERS_BUILDING_BUILD_PK;
create index RECEIVERS_BUILDING_BUILD_PK on RECEIVERS_BUILDING (BUILD_PK);

drop index if exists BUILDINGS_ERPS_ID_BAT  ;
create index BUILDINGS_ERPS_ID_BAT on  BUILDINGS_ERPS (ID_BAT);

