services:
  postgres:
    image: imresamu/postgis:17-3.5
    environment:
      # must specify password for PG Docker container image, see: https://registry.hub.docker.com/_/postgres?tab=description&page=1&name=10
      POSTGRES_USER: noisemodelling
      POSTGRES_PASSWORD: noisemodelling
      POSTGRES_DB: noisemodelling_db
    ports:
      - "5432:5432"
    # needed because the postgres container does not provide a healthcheck
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
