name: CI main

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/CI.yml
    secrets: inherit

  publish-docker:
    needs: test
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit
