name: CI main

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/CI.yml
    secrets: inherit

  # Trigger Docker build ONLY if tests pass AND it's the main branch
  publish-docker:
    needs: test
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit

  summary:
    name: Build Summary
    if: always()
    runs-on: ubuntu-latest
    needs: [test, publish-docker]
    steps:
      - name: Check status
        run: |
          # If any of the needed jobs failed, this step will fail, 
          # making the whole 'summary' job fail.
          if [ "${{ needs.test.result }}" == "failure" ] || [ "${{ needs.publish-docker.result }}" == "failure" ]; then
            echo "One of the jobs failed."
            exit 1
          fi
          echo "All jobs passed!"
