name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:16-3.4
        env:
          # must specify password for PG Docker container image, see: https://registry.hub.docker.com/_/postgres?tab=description&page=1&name=10
          POSTGRES_USER: noisemodelling
          POSTGRES_PASSWORD: noisemodelling
          POSTGRES_DB: noisemodelling_db
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      sshd:
        image: linuxserver/openssh-server:latest
        env:
          PUID: 1000
          PGID: 1000
          TZ: Etc/UTC
          USER_NAME: testuser
          PUBLIC_KEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDeviPPiHoEJnJ0QW0zbR4Uco+wI1ekLNySZ37QS/AxR0b9OyLQKQoQ04/ekT5UmwoLzNVQK9hz7Kxmg5YTFpgGSCGOGlkGOJRZQgVQ51ITzOQvz67WRkuuCKRV2g/mzWkMRWNqKag9Q8fAbIF5f3kWQNypsyROngfLnBstt4SvsbDeU+0r++vavegmYpFYh1V3MDjFibrKg+8+9BpMJ/KaPwVknaHz0SEQ8D/HUQrfhb+WsaXiQxnU0IW+7Yzp2iO3voUP/CkdX9C1KoRA9KEo0yctb+l2W7PDOxLh5TZIeXcak93TWo/SMiNT4C0zjm/9ZDGNq6HXY2z19us9NGcv test@example.com"
          SUDO_ACCESS: "true"
          PASSWORD_ACCESS: "false"
        ports:
          - 2222:2222
    steps:
      # Checkout the source code of the project
      - name: Checkout
        uses: actions/checkout@v4
      # Setup the jdk using version 11 of Adoptium Temurin
      - name: Setup java 11 using Adoptium Temurin
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Building
        run: mvn test -B
        env:
          SSH_HOST: localhost
          SSH_PORT: 2222
          SSH_USER: testuser
          SSH_KEY: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
            NhAAAAAwEAAQAAAQEA3r4jz4h6BCZydEFtM20eFHKPsCNXpCzckmd+0EvwMUdG/Tsi0CkK
            ENOP3pE+VJsKC8zVUCvYc+ysZoOWExaYBkghjhpZBjiUWUIFUOdSE8zkL8+u1kZLrgikVd
            oP5s1pDEVjaimoPUPHwGyBeX95FkDcqbMkTp4Hy5wbLbeEr7Gw3lPtK/vr2r3oJmKRWIdV
            dzA4xYm6yoPvPvQaTCfymj8FZJ2h89EhEPA/x1EK34W/lrGl4kMZ1NCFvu2M6dojt76FD/
            wpHV/QtSqEQPShKNMnLW/pdluzwzsS4eU2SHl3GpPd01qP0jIjU+AtM45v/WQxjauh12Ns
            9fbrPTRnLwAAA8jP1Gawz9RmsAAAAAdzc2gtcnNhAAABAQDeviPPiHoEJnJ0QW0zbR4Uco
            +wI1ekLNySZ37QS/AxR0b9OyLQKQoQ04/ekT5UmwoLzNVQK9hz7Kxmg5YTFpgGSCGOGlkG
            OJRZQgVQ51ITzOQvz67WRkuuCKRV2g/mzWkMRWNqKag9Q8fAbIF5f3kWQNypsyROngfLnB
            stt4SvsbDeU+0r++vavegmYpFYh1V3MDjFibrKg+8+9BpMJ/KaPwVknaHz0SEQ8D/HUQrf
            hb+WsaXiQxnU0IW+7Yzp2iO3voUP/CkdX9C1KoRA9KEo0yctb+l2W7PDOxLh5TZIeXcak9
            3TWo/SMiNT4C0zjm/9ZDGNq6HXY2z19us9NGcvAAAAAwEAAQAAAQEAizZLK2og2HcvEXnS
            xlFse1secvejzvg640XL/GN5u1LRC3PqTi9YGywevvwH+NjtbnKW34SHw+wn0+pp4YQ9f6
            +VSTsuaLT0AtVAfVAV/EoSU895dnJ42kyMaRvg1F+NSB4WBEQE4kV6ksk+IrGI/F+NioJs
            LraWKKtoUSphw2wgC1zD3+g/ReqIHsFjm7ml0z9Uy3lI1mSNY/f8AUNI/ylD+NY7ExOUKr
            TXMjsF0GhlGVMUsOPWzwYABE/l9IAQqrTM8y6ItwLNYg7QaU7M5dJIwt0ImWGHu8vG3pTP
            sLDXsq0+B2OKS/56aruxUMh8NYSQqRWzbvpmIjhL/+AAAQAAAIEAshSK3GTgv0s+2AKTvu
            B37E+a6sB/rq1SAwe1qzMTiCeUTcu4YJryjWb0HAxxxfV8cPlX9KOMdZIQPcnqDYda7Pmf
            GJ48arkfpslhlT837DifEQHUvksbR8WShlHvwJ1EBoTNINhIP46QHexycPMuxzXB35tdNA
            MJZa02dhWA9mQAAACBAP4233osUHyQWxtgcCrgRbXCMDQ+lpefv42KftHsODSlkFVsKoZv
            FzF1XGXDDSSrNqEiYtjtArmKWicZB0iQHp4hhrZ59Ne6Bxvu3GUaHk//vUNfJkDGu4VrUF
            /4ojV6mcwJibyoROwpbz3muHd4bMLZ6WGWbT0T9/pw37Pwl2VzAAAAgQDgTqzBBP5wmh/p
            g+MvfN+dOffEdalpEa71QGyu0SQT8MSq9RX7qQjkBLijxcBZVThicY6DVUxT+RUTYjMz7E
            t9UciovHTxjaytvodoAD36bn2ZRg0v8imS9ct7cknp+EU3PpvTPUZUKYGn+ARVpyuYWd/5
            R83Qu+7qV0ztWSNoVQAAABB0ZXN0QGV4YW1wbGUuY29tAQ==
            -----END OPENSSH PRIVATE KEY-----
      - name: Package
        run: mvn package
      - name: Install bsdtar
        run: |
          sudo apt-get update
          sudo apt-get install -y libarchive-tools
      - name: Unzip production artifacts
        run: |
          mkdir NoiseModellingCovadis
          # bsdtar handles .zip and supports --strip-components
          bsdtar -xvf covadis-webserver/target/*.zip --strip-components=1 -C NoiseModellingCovadis
      - name: Generate Sanitized Artifact Name
        id: sanitize
        run: |
          # Determine the raw value (Ref name if not default branch, otherwise SHA)
          if [ "${{ github.ref_name }}" != "${{ github.event.repository.default_branch }}" ]; then
          RAW_VAL="${{ github.ref_name }}"
          else
          RAW_VAL="${{ github.sha }}"
          fi
  
          # Use sed to perform replacements:
          # 1. / and \ become _
          # 2. : is removed
          # 3. * becomes x
          CLEAN_VAL=$(echo "$RAW_VAL" | sed 's/[\/\\]/_/g; s/://g; s/\*/x/g')
          
          # Set it as an environment variable for the next step
          echo "ARTIFACT_NAME=NoiseModellingCovadis-$CLEAN_VAL" >> $GITHUB_ENV
      - name: Upload distribution file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: NoiseModellingCovadis/



